-- begin ORDERSTORE_GOOD_NAME_OPTION
alter table ORDERSTORE_GOOD_NAME_OPTION add constraint FK_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS foreign key (GOODS_ID) references ORDERSTORE_GOODS(ID) on delete CASCADE^
create index IDX_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS on ORDERSTORE_GOOD_NAME_OPTION (GOODS_ID)^
-- end ORDERSTORE_GOOD_NAME_OPTION
-- begin ORDERSTORE_UNITS
alter table ORDERSTORE_UNITS add constraint FK_ORDERSTORE_UNITS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_UNITS_ON_OWNER on ORDERSTORE_UNITS (OWNER_ID)^
-- end ORDERSTORE_UNITS
-- begin ORDERSTORE_GOODS_GROUPS
alter table ORDERSTORE_GOODS_GROUPS add constraint FK_ORDERSTORE_GOODS_GROUPS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_GOODS_GROUPS_ON_OWNER on ORDERSTORE_GOODS_GROUPS (OWNER_ID)^
-- end ORDERSTORE_GOODS_GROUPS
-- begin ORDERSTORE_GOODS
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_GROUP foreign key (GROUP_ID) references ORDERSTORE_GOODS_GROUPS(ID)^
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_GOODS_ON_UNIT on ORDERSTORE_GOODS (UNIT_ID)^
create index IDX_ORDERSTORE_GOODS_ON_GROUP on ORDERSTORE_GOODS (GROUP_ID)^
create index IDX_ORDERSTORE_GOODS_ON_OWNER on ORDERSTORE_GOODS (OWNER_ID)^
-- end ORDERSTORE_GOODS
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_SEC_USER_ON_OWNER on SEC_USER (OWNER_ID)^
-- end SEC_USER
-- begin ORDERSTORE_COST_TYPE
alter table ORDERSTORE_COST_TYPE add constraint FK_ORDERSTORE_COST_TYPE_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create unique index IDX_ORDERSTORE_COST_TYPE_UK_NAME on ORDERSTORE_COST_TYPE (NAME) ^
create index IDX_ORDERSTORE_COST_TYPE_ON_OWNER on ORDERSTORE_COST_TYPE (OWNER_ID)^
-- end ORDERSTORE_COST_TYPE
-- begin ORDERSTORE_COST
alter table ORDERSTORE_COST add constraint FK_ORDERSTORE_COST_ON_COST_TYPE foreign key (COST_TYPE_ID) references ORDERSTORE_COST_TYPE(ID)^
alter table ORDERSTORE_COST add constraint FK_ORDERSTORE_COST_ON_GOOD foreign key (GOOD_ID) references ORDERSTORE_GOODS(ID) on delete CASCADE^
create index IDX_ORDERSTORE_COST_ON_COST_TYPE on ORDERSTORE_COST (COST_TYPE_ID)^
create index IDX_ORDERSTORE_COST_ON_GOOD on ORDERSTORE_COST (GOOD_ID)^
-- end ORDERSTORE_COST
-- begin ORDERSTORE_STOCK
alter table ORDERSTORE_STOCK add constraint FK_ORDERSTORE_STOCK_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_STOCK_ON_OWNER on ORDERSTORE_STOCK (OWNER_ID)^
-- end ORDERSTORE_STOCK
-- begin ORDERSTORE_STOCK_RECORD
alter table ORDERSTORE_STOCK_RECORD add constraint FK_ORDERSTORE_STOCK_RECORD_ON_STOCK_MOVEMENT foreign key (STOCK_MOVEMENT_ID) references ORDERSTORE_STOCK_MOVEMENT(ID) on delete CASCADE^
alter table ORDERSTORE_STOCK_RECORD add constraint FK_ORDERSTORE_STOCK_RECORD_ON_GOOD foreign key (GOOD_ID) references ORDERSTORE_GOODS(ID)^
create index IDX_ORDERSTORE_STOCK_RECORD_ON_STOCK_MOVEMENT on ORDERSTORE_STOCK_RECORD (STOCK_MOVEMENT_ID)^
create index IDX_ORDERSTORE_STOCK_RECORD_ON_GOOD on ORDERSTORE_STOCK_RECORD (GOOD_ID)^
-- end ORDERSTORE_STOCK_RECORD
-- begin ORDERSTORE_STOCK_MOVEMENT
alter table ORDERSTORE_STOCK_MOVEMENT add constraint FK_ORDERSTORE_STOCK_MOVEMENT_ON_STOCK foreign key (STOCK_ID) references ORDERSTORE_STOCK(ID)^
create index IDX_ORDERSTORE_STOCK_MOVEMENT_ON_STOCK on ORDERSTORE_STOCK_MOVEMENT (STOCK_ID)^
-- end ORDERSTORE_STOCK_MOVEMENT
-- begin ORDERSTORE_ROW_MATERIAL
alter table ORDERSTORE_ROW_MATERIAL add constraint FK_ORDERSTORE_ROW_MATERIAL_ON_GOOD foreign key (GOOD_ID) references ORDERSTORE_GOODS(ID)^
alter table ORDERSTORE_ROW_MATERIAL add constraint FK_ORDERSTORE_ROW_MATERIAL_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_ROW_MATERIAL add constraint FK_ORDERSTORE_ROW_MATERIAL_ON_PRODUCT_SPECIFICATION foreign key (PRODUCT_SPECIFICATION_ID) references ORDERSTORE_PRODUCT_SPECIFICATION(ID) on delete CASCADE^
create index IDX_ORDERSTORE_ROW_MATERIAL_ON_GOOD on ORDERSTORE_ROW_MATERIAL (GOOD_ID)^
create index IDX_ORDERSTORE_ROW_MATERIAL_ON_UNIT on ORDERSTORE_ROW_MATERIAL (UNIT_ID)^
create index IDX_ORDERSTORE_ROW_MATERIAL_ON_PRODUCT_SPECIFICATION on ORDERSTORE_ROW_MATERIAL (PRODUCT_SPECIFICATION_ID)^
-- end ORDERSTORE_ROW_MATERIAL
-- begin ORDERSTORE_PRODUCT_SPECIFICATION
alter table ORDERSTORE_PRODUCT_SPECIFICATION add constraint FK_ORDERSTORE_PRODUCT_SPECIFICATION_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERSTORE_GOODS(ID)^
alter table ORDERSTORE_PRODUCT_SPECIFICATION add constraint FK_ORDERSTORE_PRODUCT_SPECIFICATION_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_PRODUCT_SPECIFICATION add constraint FK_ORDERSTORE_PRODUCT_SPECIFICATION_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_PRODUCT_SPECIFICATION_ON_PRODUCT on ORDERSTORE_PRODUCT_SPECIFICATION (PRODUCT_ID)^
create index IDX_ORDERSTORE_PRODUCT_SPECIFICATION_ON_UNIT on ORDERSTORE_PRODUCT_SPECIFICATION (UNIT_ID)^
create index IDX_ORDERSTORE_PRODUCT_SPECIFICATION_ON_OWNER on ORDERSTORE_PRODUCT_SPECIFICATION (OWNER_ID)^
-- end ORDERSTORE_PRODUCT_SPECIFICATION
-- begin ORDERSTORE_ORDER_PRODUCT_MATERIAL
alter table ORDERSTORE_ORDER_PRODUCT_MATERIAL add constraint FK_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_GOOD foreign key (GOOD_ID) references ORDERSTORE_GOODS(ID)^
alter table ORDERSTORE_ORDER_PRODUCT_MATERIAL add constraint FK_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_ORDER_PRODUCT_MATERIAL add constraint FK_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_ORDER_PRODUCT foreign key (ORDER_PRODUCT_ID) references ORDERSTORE_ORDER_PRODUCT(ID) on delete CASCADE^
create index IDX_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_GOOD on ORDERSTORE_ORDER_PRODUCT_MATERIAL (GOOD_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_UNIT on ORDERSTORE_ORDER_PRODUCT_MATERIAL (UNIT_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_MATERIAL_ON_ORDER_PRODUCT on ORDERSTORE_ORDER_PRODUCT_MATERIAL (ORDER_PRODUCT_ID)^
-- end ORDERSTORE_ORDER_PRODUCT_MATERIAL
-- begin ORDERSTORE_ORDER_PRODUCT_ITEM
alter table ORDERSTORE_ORDER_PRODUCT_ITEM add constraint FK_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERSTORE_GOODS(ID)^
alter table ORDERSTORE_ORDER_PRODUCT_ITEM add constraint FK_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_ORDER_PRODUCT_ITEM add constraint FK_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_SPECIFICATION foreign key (SPECIFICATION_ID) references ORDERSTORE_PRODUCT_SPECIFICATION(ID)^
alter table ORDERSTORE_ORDER_PRODUCT_ITEM add constraint FK_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_ORDER_PRODUCT foreign key (ORDER_PRODUCT_ID) references ORDERSTORE_ORDER_PRODUCT(ID) on delete CASCADE^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_PRODUCT on ORDERSTORE_ORDER_PRODUCT_ITEM (PRODUCT_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_UNIT on ORDERSTORE_ORDER_PRODUCT_ITEM (UNIT_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_SPECIFICATION on ORDERSTORE_ORDER_PRODUCT_ITEM (SPECIFICATION_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ITEM_ON_ORDER_PRODUCT on ORDERSTORE_ORDER_PRODUCT_ITEM (ORDER_PRODUCT_ID)^
-- end ORDERSTORE_ORDER_PRODUCT_ITEM
-- begin ORDERSTORE_ORDER_PRODUCT
alter table ORDERSTORE_ORDER_PRODUCT add constraint FK_ORDERSTORE_ORDER_PRODUCT_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
alter table ORDERSTORE_ORDER_PRODUCT add constraint FK_ORDERSTORE_ORDER_PRODUCT_ON_STOCK_PRODUCT foreign key (STOCK_PRODUCT_ID) references ORDERSTORE_STOCK(ID)^
alter table ORDERSTORE_ORDER_PRODUCT add constraint FK_ORDERSTORE_ORDER_PRODUCT_ON_STOCK_MATERIALS foreign key (STOCK_MATERIALS_ID) references ORDERSTORE_STOCK(ID)^
alter table ORDERSTORE_ORDER_PRODUCT add constraint FK_ORDERSTORE_ORDER_PRODUCT_ON_STATUS foreign key (STATUS_ID) references ORDERSTORE_STATUS_ENTITY(ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ON_OWNER on ORDERSTORE_ORDER_PRODUCT (OWNER_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ON_STOCK_PRODUCT on ORDERSTORE_ORDER_PRODUCT (STOCK_PRODUCT_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ON_STOCK_MATERIALS on ORDERSTORE_ORDER_PRODUCT (STOCK_MATERIALS_ID)^
create index IDX_ORDERSTORE_ORDER_PRODUCT_ON_STATUS on ORDERSTORE_ORDER_PRODUCT (STATUS_ID)^
-- end ORDERSTORE_ORDER_PRODUCT
-- begin ORDERSTORE_STATUS_ENTITY
alter table ORDERSTORE_STATUS_ENTITY add constraint FK_ORDERSTORE_STATUS_ENTITY_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
alter table ORDERSTORE_STATUS_ENTITY add constraint FK_ORDERSTORE_STATUS_ENTITY_ON_ENTITY_TYPE foreign key (ENTITY_TYPE_ID) references ORDERSTORE_STATUS_ENTITY_TYPES(ID)^
create index IDX_ORDERSTORE_STATUS_ENTITY_ON_OWNER on ORDERSTORE_STATUS_ENTITY (OWNER_ID)^
create index IDX_ORDERSTORE_STATUS_ENTITY_ON_ENTITY_TYPE on ORDERSTORE_STATUS_ENTITY (ENTITY_TYPE_ID)^
-- end ORDERSTORE_STATUS_ENTITY
-- begin ORDERSTORE_ADDRESS_TYPES
create unique index IDX_ORDERSTORE_ADDRESS_TYPES_UK_CODE on ORDERSTORE_ADDRESS_TYPES (CODE) ^
create unique index IDX_ORDERSTORE_ADDRESS_TYPES_UK_NAME on ORDERSTORE_ADDRESS_TYPES (NAME) ^
-- end ORDERSTORE_ADDRESS_TYPES
-- begin ORDERSTORE_CONTACT_TYPE
create unique index IDX_ORDERSTORE_CONTACT_TYPE_UK_CODE on ORDERSTORE_CONTACT_TYPE (CODE) ^
create unique index IDX_ORDERSTORE_CONTACT_TYPE_UK_NAME on ORDERSTORE_CONTACT_TYPE (NAME) ^
-- end ORDERSTORE_CONTACT_TYPE
-- begin ORDERSTORE_CONTACT
alter table ORDERSTORE_CONTACT add constraint FK_ORDERSTORE_CONTACT_ON_TYPE foreign key (TYPE) references ORDERSTORE_CONTACT_TYPE(ID)^
alter table ORDERSTORE_CONTACT add constraint FK_ORDERSTORE_CONTACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERSTORE_CUSTOMER(ID) on delete CASCADE^
create index IDX_ORDERSTORE_CONTACT_ON_TYPE on ORDERSTORE_CONTACT (TYPE)^
create index IDX_ORDERSTORE_CONTACT_ON_CUSTOMER on ORDERSTORE_CONTACT (CUSTOMER_ID)^
-- end ORDERSTORE_CONTACT
-- begin ORDERSTORE_ADDRESS
alter table ORDERSTORE_ADDRESS add constraint FK_ORDERSTORE_ADDRESS_ON_ADDRESS_TYPE foreign key (ADDRESS_TYPE) references ORDERSTORE_ADDRESS_TYPES(ID)^
alter table ORDERSTORE_ADDRESS add constraint FK_ORDERSTORE_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERSTORE_CUSTOMER(ID) on delete CASCADE^
create index IDX_ORDERSTORE_ADDRESS_ON_ADDRESS_TYPE on ORDERSTORE_ADDRESS (ADDRESS_TYPE)^
create index IDX_ORDERSTORE_ADDRESS_ON_CUSTOMER on ORDERSTORE_ADDRESS (CUSTOMER_ID)^
-- end ORDERSTORE_ADDRESS
-- begin ORDERSTORE_CUSTOMER
alter table ORDERSTORE_CUSTOMER add constraint FK_ORDERSTORE_CUSTOMER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_CUSTOMER_ON_OWNER on ORDERSTORE_CUSTOMER (OWNER_ID)^
-- end ORDERSTORE_CUSTOMER
-- begin ORDERSTORE_ORDER
alter table ORDERSTORE_ORDER add constraint FK_ORDERSTORE_ORDER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
alter table ORDERSTORE_ORDER add constraint FK_ORDERSTORE_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERSTORE_CUSTOMER(ID)^
alter table ORDERSTORE_ORDER add constraint FK_ORDERSTORE_ORDER_ON_STATUS foreign key (STATUS_ID) references ORDERSTORE_STATUS_ENTITY(ID)^
create index IDX_ORDERSTORE_ORDER_ON_OWNER on ORDERSTORE_ORDER (OWNER_ID)^
create index IDX_ORDERSTORE_ORDER_ON_CUSTOMER on ORDERSTORE_ORDER (CUSTOMER_ID)^
create index IDX_ORDERSTORE_ORDER_ON_STATUS on ORDERSTORE_ORDER (STATUS_ID)^
-- end ORDERSTORE_ORDER
-- begin ORDERSTORE_ORDER_ITEM
alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERSTORE_GOODS(ID)^
alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references ORDERSTORE_ORDER(ID) on delete CASCADE^
create index IDX_ORDERSTORE_ORDER_ITEM_ON_PRODUCT on ORDERSTORE_ORDER_ITEM (PRODUCT_ID)^
create index IDX_ORDERSTORE_ORDER_ITEM_ON_UNIT on ORDERSTORE_ORDER_ITEM (UNIT_ID)^
create index IDX_ORDERSTORE_ORDER_ITEM_ON_ORDER on ORDERSTORE_ORDER_ITEM (ORDER_ID)^
-- end ORDERSTORE_ORDER_ITEM
