-- begin ORDERSTORE_GOOD_NAME_OPTION
alter table ORDERSTORE_GOOD_NAME_OPTION add constraint FK_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS foreign key (GOODS_ID) references ORDERSTORE_GOODS(ID)^
create index IDX_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS on ORDERSTORE_GOOD_NAME_OPTION (GOODS_ID)^
-- end ORDERSTORE_GOOD_NAME_OPTION
-- begin ORDERSTORE_UNITS
alter table ORDERSTORE_UNITS add constraint FK_ORDERSTORE_UNITS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_UNITS_ON_OWNER on ORDERSTORE_UNITS (OWNER_ID)^
-- end ORDERSTORE_UNITS
-- begin ORDERSTORE_GOODS_GROUPS
alter table ORDERSTORE_GOODS_GROUPS add constraint FK_ORDERSTORE_GOODS_GROUPS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_GOODS_GROUPS_ON_OWNER on ORDERSTORE_GOODS_GROUPS (OWNER_ID)^
-- end ORDERSTORE_GOODS_GROUPS
-- begin ORDERSTORE_GOODS
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID)^
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_GROUP foreign key (GROUP_ID) references ORDERSTORE_GOODS_GROUPS(ID)^
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_ORDERSTORE_GOODS_ON_UNIT on ORDERSTORE_GOODS (UNIT_ID)^
create index IDX_ORDERSTORE_GOODS_ON_GROUP on ORDERSTORE_GOODS (GROUP_ID)^
create index IDX_ORDERSTORE_GOODS_ON_OWNER on ORDERSTORE_GOODS (OWNER_ID)^
-- end ORDERSTORE_GOODS
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID)^
create index IDX_SEC_USER_ON_OWNER on SEC_USER (OWNER_ID)^
-- end SEC_USER
