alter table ORDERSTORE_GOOD_NAME_OPTION add constraint FK_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS foreign key (GOODS_ID) references ORDERSTORE_GOODS(ID);
create index IDX_ORDERSTORE_GOOD_NAME_OPTION_ON_GOODS on ORDERSTORE_GOOD_NAME_OPTION (GOODS_ID);
