alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID);
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_GROUP foreign key (GROUP_ID) references ORDERSTORE_GOODS_GROUPS(ID);
alter table ORDERSTORE_GOODS add constraint FK_ORDERSTORE_GOODS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create index IDX_ORDERSTORE_GOODS_ON_UNIT on ORDERSTORE_GOODS (UNIT_ID);
create index IDX_ORDERSTORE_GOODS_ON_GROUP on ORDERSTORE_GOODS (GROUP_ID);
create index IDX_ORDERSTORE_GOODS_ON_OWNER on ORDERSTORE_GOODS (OWNER_ID);
