alter table ORDERSTORE_COST_TYPE add constraint FK_ORDERSTORE_COST_TYPE_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create unique index IDX_ORDERSTORE_COST_TYPE_UK_NAME on ORDERSTORE_COST_TYPE (NAME) ;
create index IDX_ORDERSTORE_COST_TYPE_ON_OWNER on ORDERSTORE_COST_TYPE (OWNER_ID);
