alter table ORDERSTORE_GOODS_GROUPS add constraint FK_ORDERSTORE_GOODS_GROUPS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create index IDX_ORDERSTORE_GOODS_GROUPS_ON_OWNER on ORDERSTORE_GOODS_GROUPS (OWNER_ID);
