alter table ORDERSTORE_STOCK add constraint FK_ORDERSTORE_STOCK_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create index IDX_ORDERSTORE_STOCK_ON_OWNER on ORDERSTORE_STOCK (OWNER_ID);
