alter table ORDERSTORE_UNITS add constraint FK_ORDERSTORE_UNITS_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create index IDX_ORDERSTORE_UNITS_ON_OWNER on ORDERSTORE_UNITS (OWNER_ID);
