alter table ORDERSTORE_CUSTOMER add constraint FK_ORDERSTORE_CUSTOMER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create index IDX_ORDERSTORE_CUSTOMER_ON_OWNER on ORDERSTORE_CUSTOMER (OWNER_ID);
