alter table ORDERSTORE_CONTACT add constraint FK_ORDERSTORE_CONTACT_ON_TYPE foreign key (TYPE) references ORDERSTORE_CONTACT_TYPE(ID);
create index IDX_ORDERSTORE_CONTACT_ON_TYPE on ORDERSTORE_CONTACT (TYPE);
