alter table ORDERSTORE_CONTACT add constraint FK_ORDERSTORE_CONTACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERSTORE_CUSTOMER(ID) on delete CASCADE;
create index IDX_ORDERSTORE_CONTACT_ON_CUSTOMER on ORDERSTORE_CONTACT (CUSTOMER_ID);
