alter table ORDERSTORE_ORDER add constraint FK_ORDERSTORE_ORDER_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
alter table ORDERSTORE_ORDER add constraint FK_ORDERSTORE_ORDER_ON_STATUS foreign key (STATUS_ID) references ORDERSTORE_STATUS_ENTITY(ID);
create index IDX_ORDERSTORE_ORDER_ON_OWNER on ORDERSTORE_ORDER (OWNER_ID);
create index IDX_ORDERSTORE_ORDER_ON_STATUS on ORDERSTORE_ORDER (STATUS_ID);
