alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERSTORE_GOODS(ID);
alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_UNIT foreign key (UNIT_ID) references ORDERSTORE_UNITS(ID);
alter table ORDERSTORE_ORDER_ITEM add constraint FK_ORDERSTORE_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references ORDERSTORE_ORDER(ID) on delete CASCADE;
create index IDX_ORDERSTORE_ORDER_ITEM_ON_PRODUCT on ORDERSTORE_ORDER_ITEM (PRODUCT_ID);
create index IDX_ORDERSTORE_ORDER_ITEM_ON_UNIT on ORDERSTORE_ORDER_ITEM (UNIT_ID);
create index IDX_ORDERSTORE_ORDER_ITEM_ON_ORDER on ORDERSTORE_ORDER_ITEM (ORDER_ID);
