alter table ORDERSTORE_ADDRESS_TYPES add constraint FK_ORDERSTORE_ADDRESS_TYPES_ON_OWNER foreign key (OWNER_ID) references ORDERSTORE_OWNER(ID);
create unique index IDX_ORDERSTORE_ADDRESS_TYPES_UK_CODE on ORDERSTORE_ADDRESS_TYPES (CODE) ;
create unique index IDX_ORDERSTORE_ADDRESS_TYPES_UK_NAME on ORDERSTORE_ADDRESS_TYPES (NAME) ;
create index IDX_ORDERSTORE_ADDRESS_TYPES_ON_OWNER on ORDERSTORE_ADDRESS_TYPES (OWNER_ID);
